window.FINDING_FIELDS = [
  { key: 'title', kind: 'input', label: { en: 'Title', ar: 'العنوان' } },
  { key: 'criteria', kind: 'textarea', label: { en: 'Criteria', ar: 'المعيار' } },
  { key: 'condition', kind: 'textarea', label: { en: 'Condition', ar: 'الحالة' } },
  { key: 'cause', kind: 'textarea', label: { en: 'Cause', ar: 'السبب' } },
  { key: 'effect', kind: 'textarea', label: { en: 'Risk / Effect', ar: 'الأثر / الخطر' } },
  { key: 'recommendation', kind: 'textarea', label: { en: 'Recommendation', ar: 'التوصية' } },
];

window.UI_STRINGS = {
  en: {
    app_title: 'Internal Audit Skills Lab',
    cover_sub: "Al Rawda Trading Co. \u00b7 Internal Audit Department",
    cover_desc: 'Pick a case, review the evidence, interview the process owners, and build your finding.',
    name_placeholder: 'Enter your name to begin',
    continue_btn: 'Continue',
    universe_sub: 'Audit Universe \u00b7 Al Rawda Trading Co.',
    choose_case: 'Choose a case',
    tab_case: 'Case File', tab_interview: 'Interview', tab_findings: 'Findings', tab_verdict: 'Verdict',
    audit_brief: 'Audit brief',
    doc_restricted: 'Restricted', doc_locked_hint: 'Not yet available - keep interviewing', doc_open_hint: 'Click to open',
    back_to_case_file: '\u2190 back to case file',
    ask_placeholder: 'Ask a question...', ask_btn: 'Ask',
    interview_not_started: (name) => `Interview not started. Ask ${name} a question.`,
    evidence_unlocked: 'New evidence unlocked in the Case File:',
    evidence_referenced: 'Evidence referenced',
    add_finding: '+ Add another finding',
    submit_grading: 'Submit for grading',
    remove: 'remove',
    no_verdict: 'No submission graded yet.<br>Complete your finding(s) and submit from the Findings tab.',
    grading_loading: 'Reviewing your submission against the case facts...',
    score_line: (score, rootFound) => `SCORE: ${score} / 100 \u00b7 Root cause identified: ${rootFound ? 'Yes' : 'No'}`,
    stamp_pass: 'PASS', stamp_needswork: 'NEEDS WORK',
    all_cases: '\u2190 All cases', reset_case: 'Reset case',
    reset_confirm: 'Reset all progress for this case? This cannot be undone.',
    could_not_open: 'Could not open the case: ',
    lang_toggle: '\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
  },
  ar: {
    app_title: 'مختبر مهارات التدقيق الداخلي',
    cover_sub: 'شركة الروضة التجارية \u00b7 إدارة التدقيق الداخلي',
    cover_desc: 'اختر قضية، راجع الأدلة، قابل أصحاب العملية، وابنِ ملاحظتك الرقابية.',
    name_placeholder: 'أدخل اسمك للبدء',
    continue_btn: 'متابعة',
    universe_sub: 'خارطة التدقيق \u00b7 شركة الروضة التجارية',
    choose_case: 'اختر قضية',
    tab_case: 'ملف القضية', tab_interview: 'المقابلة', tab_findings: 'الملاحظات', tab_verdict: 'النتيجة',
    audit_brief: 'موجز التكليف',
    doc_restricted: 'غير متاح', doc_locked_hint: 'غير متاح بعد - تابع المقابلة', doc_open_hint: 'انقر للفتح',
    back_to_case_file: '\u2192 العودة إلى ملف القضية',
    ask_placeholder: 'اطرح سؤالاً...', ask_btn: 'اسأل',
    interview_not_started: (name) => `لم تبدأ المقابلة بعد. اطرح سؤالاً على ${name}.`,
    evidence_unlocked: 'تم الكشف عن دليل جديد في ملف القضية:',
    evidence_referenced: 'الأدلة المرجعية',
    add_finding: '+ إضافة ملاحظة أخرى',
    submit_grading: 'إرسال للتقييم',
    remove: 'إزالة',
    no_verdict: 'لم يتم تقييم أي إرسال بعد.<br>أكمل ملاحظتك (ملاحظاتك) وأرسلها من تبويب الملاحظات.',
    grading_loading: 'جارٍ مراجعة إجابتك مقارنةً بوقائع القضية...',
    score_line: (score, rootFound) => `الدرجة: ${score} / 100 \u00b7 تم تحديد السبب الجذري: ${rootFound ? 'نعم' : 'لا'}`,
    stamp_pass: 'ناجح', stamp_needswork: 'بحاجة إلى تحسين',
    all_cases: '\u2192 جميع القضايا', reset_case: 'إعادة تعيين القضية',
    reset_confirm: 'هل تريد إعادة تعيين كل التقدم في هذه القضية؟ لا يمكن التراجع عن هذا الإجراء.',
    could_not_open: 'تعذر فتح القضية: ',
    lang_toggle: 'English',
  },
};

window.CASES = {
  'procurement-po-split': {
    caseNumber: 'AR-2031',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Procure-to-Pay Walkthrough', ar: 'اختبار دورة الشراء حتى السداد' },
    department: { en: 'Procurement', ar: 'المشتريات' },
    listBlurb: { en: "Three purchase orders. One vendor. One day. Something doesn't add up.", ar: 'ثلاثة أوامر شراء. مورد واحد. يوم واحد. هناك ما لا يتفق.' },
    brief: {
      en: "You are the internal auditor assigned to a procure-to-pay walkthrough at Al Rawda Trading Co. Three purchase orders to the same office-supplies vendor were raised on the same day by the same requester, each just under the KD 1,000 supervisor approval limit. Review the evidence, interview the process owners, and build a finding.",
      ar: 'أنت المدقق الداخلي المكلف بتنفيذ اختبار دورة الشراء حتى السداد في شركة الروضة التجارية. تم إصدار ثلاثة أوامر شراء لنفس مورد اللوازم المكتبية في نفس اليوم من قبل نفس طالب الشراء، وكانت كل قيمة منها أقل بقليل من حد اعتماد المشرف المباشر البالغ 1,000 دينار كويتي. راجع الأدلة، قابل أصحاب العملية، وابنِ ملاحظتك الرقابية.',
    },
    documents: [
      { id: 'po-1042', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1042', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 950.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - desks, partitions']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1042', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '950.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - مكاتب، فواصل']] } },
      { id: 'po-1043', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1043', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 900.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - chairs, cabinets']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1043', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '900.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - كراسي، خزائن']] } },
      { id: 'po-1044', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1044', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 980.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - shelving, fittings']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1044', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '980.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - أرفف، تجهيزات']] } },
      { id: 'policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'Procurement Policy Section 4.2', rows: [['Level 1 - Supervisor', 'Up to KD 1,000 per purchase order'], ['Level 2 - Manager', 'KD 1,000.01 - KD 5,000'], ['Level 3 - Director', 'Above KD 5,000'], ['Note', 'Approval level is determined by the value of the purchase order.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة المشتريات، البند 4.2', rows: [['المستوى 1 - المشرف', 'حتى 1,000 د.ك لكل أمر شراء'], ['المستوى 2 - المدير', 'من 1,000.01 إلى 5,000 د.ك'], ['المستوى 3 - المدير التنفيذي', 'أكثر من 5,000 د.ك'], ['ملاحظة', 'يُحدَّد مستوى الاعتماد بناءً على قيمة أمر الشراء.']] } },
      { id: 'vendor', icon: 'building',
        en: { tag: 'Vendor Record', title: 'Vendor Master - Gulf Office Supplies', rows: [['Vendor since', '2021'], ['Bank account', 'Single account on file'], ['Related POs (last 90 days)', '7'], ['Notes', 'No prior audit exceptions on file.']] },
        ar: { tag: 'سجل المورد', title: 'البيانات الأساسية للمورد - شركة الخليج للتجهيزات المكتبية', rows: [['متعامل معه منذ', '2021'], ['الحساب البنكي', 'حساب واحد مسجل'], ['أوامر الشراء المرتبطة (آخر 90 يوماً)', '7'], ['ملاحظات', 'لا توجد ملاحظات تدقيق سابقة مسجلة.']] } },
      { id: 'email-042', icon: 'mail', locked: true,
        en: { tag: 'Correspondence', title: 'Email Thread - Procurement & Vendor', rows: [['From', 'Ahmad Salem'], ['To', 'Gulf Office Supplies (Sales)'], ['Subject', 'Re: Office fit-out order'], ['Body', "\"Let's raise this as three separate POs instead of one so it doesn't need to go to my manager - same total, just split it the way I send them.\""]] },
        ar: { tag: 'مراسلات', title: 'سلسلة بريد إلكتروني - المشتريات والمورد', rows: [['من', 'أحمد سالم'], ['إلى', 'شركة الخليج للتجهيزات المكتبية (المبيعات)'], ['الموضوع', 'الرد: طلب تجهيز المكتب'], ['النص', '"لنُصدر هذا كثلاثة أوامر شراء منفصلة بدلاً من واحد حتى لا يحتاج الأمر إلى موافقة مديري - نفس المبلغ الإجمالي، فقط قسّمه بالطريقة التي أرسلها لك."']] } },
    ],
    personas: {
      ahmad: { en: { name: 'Ahmad Salem', role: 'Procurement Officer' }, ar: { name: 'أحمد سالم', role: 'مسؤول المشتريات' } },
      fatima: { en: { name: 'Fatima Al-Otaibi', role: 'Procurement Supervisor' }, ar: { name: 'فاطمة العتيبي', role: 'مشرفة المشتريات' } },
    },
  },

  'payroll-ghost-employee': {
    caseNumber: 'AR-4417',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Payroll Continuity Review', ar: 'مراجعة استمرارية الرواتب' },
    department: { en: 'HR & Payroll', ar: 'الموارد البشرية والرواتب' },
    listBlurb: { en: "An employee left three months ago. The payslips didn't get the message.", ar: 'موظف غادر الشركة قبل ثلاثة أشهر. لكن كشوف الرواتب لم تُبلَّغ بذلك.' },
    brief: {
      en: "You are the internal auditor reviewing payroll continuity controls at Al Rawda Trading Co. A warehouse employee's termination was processed in May, but payroll records show salary payments continuing for three more months afterward. Review the evidence, interview HR and Payroll, and build a finding.",
      ar: 'أنت المدقق الداخلي المكلف بمراجعة ضوابط استمرارية الرواتب في شركة الروضة التجارية. تمت معالجة إنهاء خدمة أحد موظفي المستودع في شهر مايو، إلا أن سجلات الرواتب تُظهر استمرار صرف الراتب لثلاثة أشهر إضافية بعد ذلك. راجع الأدلة، قابل موظفي الموارد البشرية والرواتب، وابنِ ملاحظتك الرقابية.',
    },
    documents: [
      { id: 'termination-letter', icon: 'doc',
        en: { tag: 'HR Record', title: 'Termination Letter - K. Al-Haidari', rows: [['Employee', 'Khaled Al-Haidari, Warehouse Assistant'], ['Termination date', '18 May 2026'], ['Processed by', 'Noor Al-Fahad, HR Coordinator'], ['Reason', 'Resignation - notice period waived'], ['Status', 'Filed and signed by department manager']] },
        ar: { tag: 'سجل موارد بشرية', title: 'خطاب إنهاء خدمة - خ. الحيدري', rows: [['الموظف', 'خالد الحيدري، مساعد مستودع'], ['تاريخ إنهاء الخدمة', '18 مايو 2026'], ['تمت المعالجة من قبل', 'نور الفهد، منسقة الموارد البشرية'], ['السبب', 'استقالة - تم التنازل عن فترة الإشعار'], ['الحالة', 'مؤرشف وموقّع من مدير القسم']] } },
      { id: 'payroll-register', icon: 'doc',
        en: { tag: 'Payroll Register', title: 'Payroll Register - Jun to Aug 2026', rows: [['Employee', 'Khaled Al-Haidari (ID 3391)'], ['June 2026', 'KD 420.000 paid'], ['July 2026', 'KD 420.000 paid'], ['August 2026', 'KD 420.000 paid'], ['Status field', 'Active (unchanged since March 2026)']] },
        ar: { tag: 'سجل الرواتب', title: 'سجل الرواتب - يونيو إلى أغسطس 2026', rows: [['الموظف', 'خالد الحيدري (الرقم الوظيفي 3391)'], ['يونيو 2026', 'تم صرف 420.000 د.ك'], ['يوليو 2026', 'تم صرف 420.000 د.ك'], ['أغسطس 2026', 'تم صرف 420.000 د.ك'], ['حقل الحالة', 'نشط (دون تغيير منذ مارس 2026)']] } },
      { id: 'hr-policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'HR Policy Section 7.3 - Termination Processing', rows: [['Step 1', 'Department manager submits termination request to HR'], ['Step 2', 'HR Coordinator updates employee status and notifies Payroll within 3 working days'], ['Step 3', 'Payroll removes employee from the next pay run'], ['Note', 'The HR Coordinator role has system access to both HR records and payroll status flags.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة الموارد البشرية، البند 7.3 - إجراءات إنهاء الخدمة', rows: [['الخطوة 1', 'يقدّم مدير القسم طلب إنهاء الخدمة إلى الموارد البشرية'], ['الخطوة 2', 'يقوم منسق الموارد البشرية بتحديث حالة الموظف وإبلاغ إدارة الرواتب خلال 3 أيام عمل'], ['الخطوة 3', 'تقوم إدارة الرواتب بإزالة الموظف من دورة الصرف التالية'], ['ملاحظة', 'يملك منسق الموارد البشرية صلاحية الوصول في النظام إلى سجلات الموارد البشرية وإلى مؤشرات حالة الرواتب معاً.']] } },
      { id: 'attendance', icon: 'building',
        en: { tag: 'Attendance Record', title: 'Biometric Attendance Log - K. Al-Haidari', rows: [['Last recorded entry', '17 May 2026'], ['June - August 2026', 'No entries recorded'], ['System notes', 'No leave or remote-work exception on file for this period.']] },
        ar: { tag: 'سجل الحضور', title: 'سجل الحضور البيومتري - خ. الحيدري', rows: [['آخر تسجيل حضور', '17 مايو 2026'], ['يونيو - أغسطس 2026', 'لا توجد أي تسجيلات'], ['ملاحظات النظام', 'لا يوجد إذن إجازة أو استثناء عمل عن بُعد مسجل لهذه الفترة.']] } },
      { id: 'bank-record', icon: 'mail', locked: true,
        en: { tag: 'Bank Deposit Record', title: 'Payroll Bank Transfer Detail', rows: [['Payee name on file', 'Khaled Al-Haidari'], ['Account number', 'Changed on 20 May 2026, two days after termination'], ['New account holder', 'Matches an account belonging to Noor Al-Fahad, HR Coordinator'], ['Change requested via', 'Employee self-service portal, logged in as Khaled Al-Haidari']] },
        ar: { tag: 'سجل الإيداع البنكي', title: 'تفاصيل التحويل البنكي للراتب', rows: [['اسم المستفيد المسجل', 'خالد الحيدري'], ['رقم الحساب', 'تم تغييره في 20 مايو 2026، أي بعد يومين من إنهاء الخدمة'], ['صاحب الحساب الجديد', 'يتطابق مع حساب يعود لنور الفهد، منسقة الموارد البشرية'], ['طلب التغيير عبر', 'بوابة الخدمة الذاتية للموظفين، بتسجيل دخول باسم خالد الحيدري']] } },
    ],
    personas: {
      noor: { en: { name: 'Noor Al-Fahad', role: 'HR Coordinator' }, ar: { name: 'نور الفهد', role: 'منسقة الموارد البشرية' } },
      hamad: { en: { name: 'Hamad Al-Sabah', role: 'Payroll Manager' }, ar: { name: 'حمد الصباح', role: 'مدير الرواتب' } },
    },
  },
};

window.CASE_LIST = Object.keys(window.CASES).map((id) => {
  const c = window.CASES[id];
  return { id: id, caseNumber: c.caseNumber, title: c.title, department: c.department, listBlurb: c.listBlurb };
});
