window.FINDING_FIELDS = [
  { key: 'title', kind: 'input', label: { en: 'Title', ar: 'العنوان' } },
  { key: 'criteria', kind: 'textarea', label: { en: 'Criteria', ar: 'المعيار' } },
  { key: 'condition', kind: 'textarea', label: { en: 'Condition', ar: 'الحالة' } },
  { key: 'cause', kind: 'textarea', label: { en: 'Cause', ar: 'السبب' } },
  { key: 'effect', kind: 'textarea', label: { en: 'Risk / Effect', ar: 'الأثر / الخطر' } },
  { key: 'recommendation', kind: 'textarea', label: { en: 'Recommendation', ar: 'التوصية' } },
];

window.UI_STRINGS = {
  en: {
    app_title: 'Internal Audit Skills Lab',
    cover_sub: "Al Rawda Trading Co. \u00b7 Internal Audit Department",
    cover_desc: 'Pick a case, review the evidence, interview the process owners, and build your finding.',
    name_placeholder: 'Enter your name to begin',
    continue_btn: 'Continue',
    universe_sub: 'Audit Universe \u00b7 Al Rawda Trading Co.',
    choose_case: 'Choose a case',
    tab_case: 'Case File', tab_interview: 'Interview', tab_findings: 'Findings', tab_verdict: 'Verdict',
    audit_brief: 'Audit brief',
    doc_restricted: 'Restricted', doc_locked_hint: 'Not yet available - keep interviewing', doc_open_hint: 'Click to open',
    back_to_case_file: '\u2190 back to case file',
    ask_placeholder: 'Ask a question...', ask_btn: 'Ask',
    interview_not_started: (name) => `Interview not started. Ask ${name} a question.`,
    evidence_unlocked: 'New evidence unlocked in the Case File:',
    evidence_referenced: 'Evidence referenced',
    add_finding: '+ Add another finding',
    submit_grading: 'Submit for grading',
    remove: 'remove',
    no_verdict: 'No submission graded yet.<br>Complete your finding(s) and submit from the Findings tab.',
    grading_loading: 'Reviewing your submission against the case facts...',
    score_line: (score, rootFound) => `SCORE: ${score} / 100 \u00b7 Root cause identified: ${rootFound ? 'Yes' : 'No'}`,
    stamp_pass: 'PASS', stamp_needswork: 'NEEDS WORK',
    all_cases: '\u2190 All cases', reset_case: 'Reset case',
    reset_confirm: 'Reset all progress for this case? This cannot be undone.',
    could_not_open: 'Could not open the case: ',
    lang_toggle: '\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
  },
  ar: {
    app_title: 'مختبر مهارات التدقيق الداخلي',
    cover_sub: 'شركة الروضة التجارية \u00b7 إدارة التدقيق الداخلي',
    cover_desc: 'اختر قضية، راجع الأدلة، قابل أصحاب العملية، وابنِ ملاحظتك الرقابية.',
    name_placeholder: 'أدخل اسمك للبدء',
    continue_btn: 'متابعة',
    universe_sub: 'خارطة التدقيق \u00b7 شركة الروضة التجارية',
    choose_case: 'اختر قضية',
    tab_case: 'ملف القضية', tab_interview: 'المقابلة', tab_findings: 'الملاحظات', tab_verdict: 'النتيجة',
    audit_brief: 'موجز التكليف',
    doc_restricted: 'غير متاح', doc_locked_hint: 'غير متاح بعد - تابع المقابلة', doc_open_hint: 'انقر للفتح',
    back_to_case_file: '\u2192 العودة إلى ملف القضية',
    ask_placeholder: 'اطرح سؤالاً...', ask_btn: 'اسأل',
    interview_not_started: (name) => `لم تبدأ المقابلة بعد. اطرح سؤالاً على ${name}.`,
    evidence_unlocked: 'تم الكشف عن دليل جديد في ملف القضية:',
    evidence_referenced: 'الأدلة المرجعية',
    add_finding: '+ إضافة ملاحظة أخرى',
    submit_grading: 'إرسال للتقييم',
    remove: 'إزالة',
    no_verdict: 'لم يتم تقييم أي إرسال بعد.<br>أكمل ملاحظتك (ملاحظاتك) وأرسلها من تبويب الملاحظات.',
    grading_loading: 'جارٍ مراجعة إجابتك مقارنةً بوقائع القضية...',
    score_line: (score, rootFound) => `الدرجة: ${score} / 100 \u00b7 تم تحديد السبب الجذري: ${rootFound ? 'نعم' : 'لا'}`,
    stamp_pass: 'ناجح', stamp_needswork: 'بحاجة إلى تحسين',
    all_cases: '\u2192 جميع القضايا', reset_case: 'إعادة تعيين القضية',
    reset_confirm: 'هل تريد إعادة تعيين كل التقدم في هذه القضية؟ لا يمكن التراجع عن هذا الإجراء.',
    could_not_open: 'تعذر فتح القضية: ',
    lang_toggle: 'English',
  },
};

window.CASES = {
  'procurement-po-split': {
    caseNumber: 'AR-2031',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Procure-to-Pay Walkthrough', ar: 'اختبار دورة الشراء حتى السداد' },
    department: { en: 'Procurement', ar: 'المشتريات' },
    listBlurb: { en: "Three purchase orders. One vendor. One day. Something doesn't add up.", ar: 'ثلاثة أوامر شراء. مورد واحد. يوم واحد. هناك ما لا يتفق.' },
    brief: {
      en: "You are the internal auditor assigned to a procure-to-pay walkthrough at Al Rawda Trading Co. Three purchase orders to the same office-supplies vendor were raised on the same day by the same requester, each just under the KD 1,000 supervisor approval limit. Review the evidence, interview the process owners, and build a finding.",
      ar: 'أنت المدقق الداخلي المكلف بتنفيذ اختبار دورة الشراء حتى السداد في شركة الروضة التجارية. تم إصدار ثلاثة أوامر شراء لنفس مورد اللوازم المكتبية في نفس اليوم من قبل نفس طالب الشراء، وكانت كل قيمة منها أقل بقليل من حد اعتماد المشرف المباشر البالغ 1,000 دينار كويتي. راجع الأدلة، قابل أصحاب العملية، وابنِ ملاحظتك الرقابية.',
    },
    documents: [
      { id: 'po-1042', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1042', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 950.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - desks, partitions']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1042', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '950.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - مكاتب، فواصل']] } },
      { id: 'po-1043', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1043', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 900.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - chairs, cabinets']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1043', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '900.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - كراسي، خزائن']] } },
      { id: 'po-1044', icon: 'doc',
        en: { tag: 'Purchase Order', title: 'PO-1044', rows: [['Vendor', 'Gulf Office Supplies W.L.L.'], ['Requester', 'Ahmad Salem, Procurement Officer'], ['Amount', 'KD 980.000'], ['Date raised', '12 Aug 2026'], ['Approved by', 'Fatima Al-Otaibi, Supervisor'], ['Items', 'Office furniture - shelving, fittings']] },
        ar: { tag: 'أمر شراء', title: 'أمر الشراء 1044', rows: [['المورد', 'شركة الخليج للتجهيزات المكتبية ذ.م.م'], ['طالب الشراء', 'أحمد سالم، مسؤول المشتريات'], ['المبلغ', '980.000 د.ك'], ['تاريخ الإصدار', '12 أغسطس 2026'], ['اعتمد من قبل', 'فاطمة العتيبي، المشرفة'], ['الأصناف', 'أثاث مكتبي - أرفف، تجهيزات']] } },
      { id: 'policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'Procurement Policy Section 4.2', rows: [['Level 1 - Supervisor', 'Up to KD 1,000 per purchase order'], ['Level 2 - Manager', 'KD 1,000.01 - KD 5,000'], ['Level 3 - Director', 'Above KD 5,000'], ['Note', 'Approval level is determined by the value of the purchase order.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة المشتريات، البند 4.2', rows: [['المستوى 1 - المشرف', 'حتى 1,000 د.ك لكل أمر شراء'], ['المستوى 2 - المدير', 'من 1,000.01 إلى 5,000 د.ك'], ['المستوى 3 - المدير التنفيذي', 'أكثر من 5,000 د.ك'], ['ملاحظة', 'يُحدَّد مستوى الاعتماد بناءً على قيمة أمر الشراء.']] } },
      { id: 'vendor', icon: 'building',
        en: { tag: 'Vendor Record', title: 'Vendor Master - Gulf Office Supplies', rows: [['Vendor since', '2021'], ['Bank account', 'Single account on file'], ['Related POs (last 90 days)', '7'], ['Notes', 'No prior audit exceptions on file.']] },
        ar: { tag: 'سجل المورد', title: 'البيانات الأساسية للمورد - شركة الخليج للتجهيزات المكتبية', rows: [['متعامل معه منذ', '2021'], ['الحساب البنكي', 'حساب واحد مسجل'], ['أوامر الشراء المرتبطة (آخر 90 يوماً)', '7'], ['ملاحظات', 'لا توجد ملاحظات تدقيق سابقة مسجلة.']] } },
      { id: 'email-042', icon: 'mail', locked: true,
        en: { tag: 'Correspondence', title: 'Email Thread - Procurement & Vendor', rows: [['From', 'Ahmad Salem'], ['To', 'Gulf Office Supplies (Sales)'], ['Subject', 'Re: Office fit-out order'], ['Body', "\"Let's raise this as three separate POs instead of one so it doesn't need to go to my manager - same total, just split it the way I send them.\""]] },
        ar: { tag: 'مراسلات', title: 'سلسلة بريد إلكتروني - المشتريات والمورد', rows: [['من', 'أحمد سالم'], ['إلى', 'شركة الخليج للتجهيزات المكتبية (المبيعات)'], ['الموضوع', 'الرد: طلب تجهيز المكتب'], ['النص', '"لنُصدر هذا كثلاثة أوامر شراء منفصلة بدلاً من واحد حتى لا يحتاج الأمر إلى موافقة مديري - نفس المبلغ الإجمالي، فقط قسّمه بالطريقة التي أرسلها لك."']] } },
    ],
    personas: {
      ahmad: { en: { name: 'Ahmad Salem', role: 'Procurement Officer' }, ar: { name: 'أحمد سالم', role: 'مسؤول المشتريات' } },
      fatima: { en: { name: 'Fatima Al-Otaibi', role: 'Procurement Supervisor' }, ar: { name: 'فاطمة العتيبي', role: 'مشرفة المشتريات' } },
    },
  },

  'payroll-ghost-employee': {
    caseNumber: 'AR-4417',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Payroll Continuity Review', ar: 'مراجعة استمرارية الرواتب' },
    department: { en: 'HR & Payroll', ar: 'الموارد البشرية والرواتب' },
    listBlurb: { en: "An employee left three months ago. The payslips didn't get the message.", ar: 'موظف غادر الشركة قبل ثلاثة أشهر. لكن كشوف الرواتب لم تُبلَّغ بذلك.' },
    brief: {
      en: "You are the internal auditor reviewing payroll continuity controls at Al Rawda Trading Co. A warehouse employee's termination was processed in May, but payroll records show salary payments continuing for three more months afterward. Review the evidence, interview HR and Payroll, and build a finding.",
      ar: 'أنت المدقق الداخلي المكلف بمراجعة ضوابط استمرارية الرواتب في شركة الروضة التجارية. تمت معالجة إنهاء خدمة أحد موظفي المستودع في شهر مايو، إلا أن سجلات الرواتب تُظهر استمرار صرف الراتب لثلاثة أشهر إضافية بعد ذلك. راجع الأدلة، قابل موظفي الموارد البشرية والرواتب، وابنِ ملاحظتك الرقابية.',
    },
    documents: [
      { id: 'termination-letter', icon: 'doc',
        en: { tag: 'HR Record', title: 'Termination Letter - K. Al-Haidari', rows: [['Employee', 'Khaled Al-Haidari, Warehouse Assistant'], ['Termination date', '18 May 2026'], ['Processed by', 'Noor Al-Fahad, HR Coordinator'], ['Reason', 'Resignation - notice period waived'], ['Status', 'Filed and signed by department manager']] },
        ar: { tag: 'سجل موارد بشرية', title: 'خطاب إنهاء خدمة - خ. الحيدري', rows: [['الموظف', 'خالد الحيدري، مساعد مستودع'], ['تاريخ إنهاء الخدمة', '18 مايو 2026'], ['تمت المعالجة من قبل', 'نور الفهد، منسقة الموارد البشرية'], ['السبب', 'استقالة - تم التنازل عن فترة الإشعار'], ['الحالة', 'مؤرشف وموقّع من مدير القسم']] } },
      { id: 'payroll-register', icon: 'doc',
        en: { tag: 'Payroll Register', title: 'Payroll Register - Jun to Aug 2026', rows: [['Employee', 'Khaled Al-Haidari (ID 3391)'], ['June 2026', 'KD 420.000 paid'], ['July 2026', 'KD 420.000 paid'], ['August 2026', 'KD 420.000 paid'], ['Status field', 'Active (unchanged since March 2026)']] },
        ar: { tag: 'سجل الرواتب', title: 'سجل الرواتب - يونيو إلى أغسطس 2026', rows: [['الموظف', 'خالد الحيدري (الرقم الوظيفي 3391)'], ['يونيو 2026', 'تم صرف 420.000 د.ك'], ['يوليو 2026', 'تم صرف 420.000 د.ك'], ['أغسطس 2026', 'تم صرف 420.000 د.ك'], ['حقل الحالة', 'نشط (دون تغيير منذ مارس 2026)']] } },
      { id: 'hr-policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'HR Policy Section 7.3 - Termination Processing', rows: [['Step 1', 'Department manager submits termination request to HR'], ['Step 2', 'HR Coordinator updates employee status and notifies Payroll within 3 working days'], ['Step 3', 'Payroll removes employee from the next pay run'], ['Note', 'The HR Coordinator role has system access to both HR records and payroll status flags.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة الموارد البشرية، البند 7.3 - إجراءات إنهاء الخدمة', rows: [['الخطوة 1', 'يقدّم مدير القسم طلب إنهاء الخدمة إلى الموارد البشرية'], ['الخطوة 2', 'يقوم منسق الموارد البشرية بتحديث حالة الموظف وإبلاغ إدارة الرواتب خلال 3 أيام عمل'], ['الخطوة 3', 'تقوم إدارة الرواتب بإزالة الموظف من دورة الصرف التالية'], ['ملاحظة', 'يملك منسق الموارد البشرية صلاحية الوصول في النظام إلى سجلات الموارد البشرية وإلى مؤشرات حالة الرواتب معاً.']] } },
      { id: 'attendance', icon: 'building',
        en: { tag: 'Attendance Record', title: 'Biometric Attendance Log - K. Al-Haidari', rows: [['Last recorded entry', '17 May 2026'], ['June - August 2026', 'No entries recorded'], ['System notes', 'No leave or remote-work exception on file for this period.']] },
        ar: { tag: 'سجل الحضور', title: 'سجل الحضور البيومتري - خ. الحيدري', rows: [['آخر تسجيل حضور', '17 مايو 2026'], ['يونيو - أغسطس 2026', 'لا توجد أي تسجيلات'], ['ملاحظات النظام', 'لا يوجد إذن إجازة أو استثناء عمل عن بُعد مسجل لهذه الفترة.']] } },
      { id: 'bank-record', icon: 'mail', locked: true,
        en: { tag: 'Bank Deposit Record', title: 'Payroll Bank Transfer Detail', rows: [['Payee name on file', 'Khaled Al-Haidari'], ['Account number', 'Changed on 20 May 2026, two days after termination'], ['New account holder', 'Matches an account belonging to Noor Al-Fahad, HR Coordinator'], ['Change requested via', 'Employee self-service portal, logged in as Khaled Al-Haidari']] },
        ar: { tag: 'سجل الإيداع البنكي', title: 'تفاصيل التحويل البنكي للراتب', rows: [['اسم المستفيد المسجل', 'خالد الحيدري'], ['رقم الحساب', 'تم تغييره في 20 مايو 2026، أي بعد يومين من إنهاء الخدمة'], ['صاحب الحساب الجديد', 'يتطابق مع حساب يعود لنور الفهد، منسقة الموارد البشرية'], ['طلب التغيير عبر', 'بوابة الخدمة الذاتية للموظفين، بتسجيل دخول باسم خالد الحيدري']] } },
    ],
    personas: {
      noor: { en: { name: 'Noor Al-Fahad', role: 'HR Coordinator' }, ar: { name: 'نور الفهد', role: 'منسقة الموارد البشرية' } },
      hamad: { en: { name: 'Hamad Al-Sabah', role: 'Payroll Manager' }, ar: { name: 'حمد الصباح', role: 'مدير الرواتب' } },
    },
  },

  'inventory-writeoff-fraud': {
    caseNumber: 'AR-5528',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Inventory Write-Off Review', ar: 'مراجعة شطب المخزون' },
    department: { en: 'Warehouse & Inventory', ar: 'المستودعات والمخزون' },
    listBlurb: { en: "Good stock keeps getting marked 'damaged.' Where does it actually go?", ar: "بضاعة سليمة يتكرر تصنيفها بأنها 'تالفة'. أين تذهب فعلياً؟" },
    brief: {
      en: "You are the internal auditor reviewing inventory write-off controls at Al Rawda Trading Co. Warehouse records show a pattern of large 'damaged/expired' stock write-offs approved for one warehouse controller, with no matching destruction records. Review the evidence, interview warehouse and finance staff, and build a finding.",
      ar: "أنت المدقق الداخلي المكلف بمراجعة ضوابط شطب المخزون في شركة الروضة التجارية. تُظهر سجلات المستودع نمطاً من عمليات شطب كبيرة لبضاعة 'تالفة/منتهية الصلاحية' معتمدة لصالح أحد مراقبي المستودع، دون وجود سجلات إتلاف مطابقة لها. راجع الأدلة، قابل موظفي المستودع والمالية، وابنِ ملاحظتك الرقابية.",
    },
    documents: [
      { id: 'writeoff-request', icon: 'doc',
        en: { tag: 'Write-Off Request', title: 'Write-Off Request Form - Batch WO-118', rows: [['Submitted by', 'Yousef Al-Ansari, Warehouse Controller'], ['Date', '03 Jul 2026'], ['Product', 'Assorted canned goods, 200 units'], ['Reason given', 'Damaged in storage - water leak'], ['Approved by', 'Reem Al-Fadhli, Inventory & Finance Analyst']] },
        ar: { tag: 'طلب شطب', title: 'نموذج طلب شطب - الدفعة رقم WO-118', rows: [['مقدَّم من', 'يوسف الأنصاري، مراقب المستودع'], ['التاريخ', '03 يوليو 2026'], ['المنتج', 'معلبات متنوعة، 200 وحدة'], ['السبب المذكور', 'تلف أثناء التخزين - تسرب مياه'], ['اعتمد من قبل', 'ريم الفاضلي، محللة المخزون والمالية']] } },
      { id: 'writeoff-log', icon: 'doc',
        en: { tag: 'Write-Off Log', title: 'Write-Off Log - Last 6 Months', rows: [['Yousef Al-Ansari (Warehouse Controller)', '5 write-offs, total KD 3,150'], ['Other warehouse staff (avg.)', '1 write-off, total KD 240'], ['Pattern', "Each of Yousef's write-offs is just under the KD 700 value that would require a second approver"]] },
        ar: { tag: 'سجل الشطب', title: 'سجل الشطب - آخر 6 أشهر', rows: [['يوسف الأنصاري (مراقب المستودع)', '5 عمليات شطب، بإجمالي 3,150 د.ك'], ['بقية موظفي المستودع (بالمتوسط)', 'عملية شطب واحدة، بإجمالي 240 د.ك'], ['النمط الملاحظ', 'كل عملية شطب ليوسف تقل بقليل عن قيمة 700 د.ك التي تستوجب معتمِداً ثانياً']] } },
      { id: 'disposal-policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'Warehouse Disposal Policy Section 5.1', rows: [['Under KD 700', 'Warehouse Controller may approve and dispose'], ['KD 700 and above', 'Requires a second approver (Finance) and a witnessed destruction log'], ['Destruction log', 'Must be signed by two employees present at disposal'], ['Note', 'Photographic evidence is required for all destroyed batches above KD 500.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة إتلاف المستودع، البند 5.1', rows: [['أقل من 700 د.ك', 'يجوز لمراقب المستودع الاعتماد والتخلص بنفسه'], ['700 د.ك فأكثر', 'يتطلب معتمِداً ثانياً (من المالية) وسجل إتلاف موثّق بشهود'], ['سجل الإتلاف', 'يجب أن يوقّعه موظفان حاضران عند التخلص من البضاعة'], ['ملاحظة', 'يُشترط توثيق مصوَّر لكل دفعة متلفة تتجاوز قيمتها 500 د.ك.']] } },
      { id: 'cycle-count', icon: 'building',
        en: { tag: 'Cycle Count Report', title: 'Cycle Count Variance Report - Jun 2026', rows: [['Recorded inventory (system)', 'Matches write-off records'], ["Physical destruction log entries", "0 for any of Yousef's 5 write-offs"], ['Variance flagged by', 'Quarterly cycle count team'], ['Note', 'No destruction log on file for any write-off above KD 500 this year.']] },
        ar: { tag: 'تقرير الجرد الدوري', title: 'تقرير فروقات الجرد الدوري - يونيو 2026', rows: [['المخزون المسجل (النظام)', 'مطابق لسجلات الشطب'], ['سجلات الإتلاف الفعلية', 'لا يوجد أي سجل لأي من عمليات الشطب الخمس ليوسف'], ['الجهة التي رصدت الفارق', 'فريق الجرد الدوري الفصلي'], ['ملاحظة', 'لا يوجد سجل إتلاف موثّق لأي عملية شطب تتجاوز 500 د.ك هذا العام.']] } },
      { id: 'buyer-messages', icon: 'mail', locked: true,
        en: { tag: 'Correspondence', title: 'Message Thread - Yousef & External Buyer', rows: [['From', 'Yousef Al-Ansari'], ['To', 'Contact saved as "Abu Sager - Market"'], ['Content', '"Same as last time, the canned stuff. I\'ll mark it damaged in the system, come by after 6pm."'], ['Date', '02 Jul 2026, the evening before the write-off was filed']] },
        ar: { tag: 'مراسلات', title: 'سلسلة رسائل - يوسف ومشترٍ خارجي', rows: [['من', 'يوسف الأنصاري'], ['إلى', 'جهة اتصال محفوظة باسم "أبو ساجر - السوق"'], ['المحتوى', '"نفس الطلبية السابقة، المعلبات. بسجلها تالفة بالنظام، تعال بعد الساعة 6 مساءً."'], ['التاريخ', '02 يوليو 2026، مساء اليوم السابق لتقديم طلب الشطب']] } },
    ],
    personas: {
      yousef: { en: { name: 'Yousef Al-Ansari', role: 'Warehouse Controller' }, ar: { name: 'يوسف الأنصاري', role: 'مراقب المستودع' } },
      reem: { en: { name: 'Reem Al-Fadhli', role: 'Inventory & Finance Analyst' }, ar: { name: 'ريم الفاضلي', role: 'محللة المخزون والمالية' } },
    },
  },

  'it-change-management': {
    caseNumber: 'AR-6091',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Unauthorized Production Change', ar: 'تغيير غير مصرّح به في بيئة الإنتاج' },
    department: { en: 'Information Technology', ar: 'تقنية المعلومات' },
    listBlurb: { en: "A 90% discount code went live. Nobody remembers approving it.", ar: 'كود خصم بنسبة 90% أصبح فعّالاً على الموقع. لا أحد يتذكر أنه اعتمده.' },
    brief: {
      en: "You are the internal auditor reviewing change management controls in the IT department at Al Rawda Trading Co. A steep discount code went live on the online store with no linked change request, and a spike of heavily discounted orders followed before it was caught. Review the evidence, interview IT staff, and build a finding.",
      ar: 'أنت المدقق الداخلي المكلف بمراجعة ضوابط إدارة التغيير في إدارة تقنية المعلومات بشركة الروضة التجارية. تم تفعيل كود خصم كبير على المتجر الإلكتروني دون وجود طلب تغيير مرتبط به، وتلا ذلك ارتفاع ملحوظ في الطلبات المخفَّضة بشكل كبير قبل اكتشاف الأمر. راجع الأدلة، قابل موظفي تقنية المعلومات، وابنِ ملاحظتك الرقابية.',
    },
    documents: [
      { id: 'deploy-log', icon: 'doc',
        en: { tag: 'Deployment Record', title: 'Production Deployment Log - 14 Jul 2026', rows: [['Deployed by', 'Faisal Al-Duwaisan, Software Developer'], ['Linked change ticket', 'N/A'], ['Commit message', '"pricing update"'], ['Environment', 'Production (live store)']] },
        ar: { tag: 'سجل النشر', title: 'سجل نشر بيئة الإنتاج - 14 يوليو 2026', rows: [['تم النشر من قبل', 'فيصل الدويسان، مطوّر برمجيات'], ['طلب التغيير المرتبط', 'لا يوجد'], ['رسالة الإيداع (Commit)', '"تحديث أسعار"'], ['البيئة', 'بيئة الإنتاج (المتجر المباشر)']] } },
      { id: 'change-policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'IT Change Management Policy Section 3.2', rows: [['Step 1', 'Developer opens a Change Request (CR) ticket describing the change'], ['Step 2', 'A peer reviews the code'], ['Step 3', 'Change Advisory Board (CAB) approves before deployment'], ['Note', 'No change may be deployed to production without a linked, approved CR ticket.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة إدارة التغيير في تقنية المعلومات، البند 3.2', rows: [['الخطوة 1', 'يفتح المطوّر طلب تغيير (CR) يوضّح التغيير المطلوب'], ['الخطوة 2', 'يقوم زميل بمراجعة الكود'], ['الخطوة 3', 'تعتمد لجنة استشارية للتغيير (CAB) الطلب قبل النشر'], ['ملاحظة', 'لا يجوز نشر أي تغيير في بيئة الإنتاج دون طلب تغيير معتمد ومرتبط به.']] } },
      { id: 'sales-spike', icon: 'building',
        en: { tag: 'Sales Report', title: 'Discount Code Usage Report - 14 to 17 Jul 2026', rows: [['Code "FRIEND90"', '90% off, used 23 times'], ['All other active codes (avg.)', '10-15% off, used 4 times each'], ['Total discount value from FRIEND90', 'KD 1,780'], ['Marketing record for FRIEND90', 'None on file']] },
        ar: { tag: 'تقرير المبيعات', title: 'تقرير استخدام أكواد الخصم - 14 إلى 17 يوليو 2026', rows: [['كود "FRIEND90"', 'خصم 90%، استُخدم 23 مرة'], ['بقية الأكواد الفعّالة (بالمتوسط)', 'خصم 10-15%، استُخدم كل منها 4 مرات'], ['إجمالي قيمة الخصم من FRIEND90', '1,780 د.ك'], ['سجل تسويقي لكود FRIEND90', 'لا يوجد']] } },
      { id: 'access-record', icon: 'doc',
        en: { tag: 'Access Record', title: 'System Permissions - F. Al-Duwaisan', rows: [['Developer access', 'Can write and commit code'], ['Production deploy access', 'Can push changes directly to the live environment'], ['Segregation check', 'Same account holds both permissions - no independent deploy role'], ['Access granted', 'Standard since joining, never reviewed']] },
        ar: { tag: 'سجل الصلاحيات', title: 'صلاحيات النظام - ف. الدويسان', rows: [['صلاحية المطوّر', 'كتابة وإيداع الكود (Commit)'], ['صلاحية النشر في بيئة الإنتاج', 'نشر التغييرات مباشرة في البيئة المباشرة'], ['فحص الفصل بين المهام', 'نفس الحساب يملك الصلاحيتين معاً - لا يوجد دور نشر مستقل'], ['منح الصلاحية', 'ممنوحة بشكل معتاد منذ الالتحاق، ولم تُراجَع منذ ذلك الحين']] } },
      { id: 'chat-thread', icon: 'mail', locked: true,
        en: { tag: 'Correspondence', title: 'Message Thread - Faisal & Friends', rows: [['From', 'Faisal Al-Duwaisan'], ['To', 'Group chat "Gym Crew"'], ['Content', '"Use FRIEND90 at checkout, 90% off, works till the weekend. Don\'t post it anywhere public though."'], ['Date', '14 Jul 2026, same day as the deployment']] },
        ar: { tag: 'مراسلات', title: 'سلسلة رسائل - فيصل والأصدقاء', rows: [['من', 'فيصل الدويسان'], ['إلى', 'مجموعة دردشة "شلة الجيم"'], ['المحتوى', '"استخدموا كود FRIEND90 عند الدفع، خصم 90%، شغّال لنهاية الأسبوع. بس لا تنشرونه بأي مكان عام."'], ['التاريخ', '14 يوليو 2026، نفس يوم النشر']] } },
    ],
    personas: {
      faisal: { en: { name: 'Faisal Al-Duwaisan', role: 'Software Developer' }, ar: { name: 'فيصل الدويسان', role: 'مطوّر برمجيات' } },
      mona: { en: { name: 'Mona Al-Kandari', role: 'IT Operations Manager' }, ar: { name: 'منى الكندري', role: 'مديرة عمليات تقنية المعلومات' } },
    },
  },

  'revenue-credit-note-fraud': {
    caseNumber: 'AR-7204',
    company: { en: 'Al Rawda Trading Co.', ar: 'شركة الروضة التجارية' },
    title: { en: 'Sales Returns & Credit Note Review', ar: 'مراجعة مرتجعات المبيعات وإشعارات الدائن' },
    department: { en: 'Sales / Revenue', ar: 'المبيعات / الإيرادات' },
    listBlurb: { en: "One customer's 'returns' never actually came back to the warehouse.", ar: "'مرتجعات' أحد العملاء لم تصل فعلياً إلى المستودع." },
    brief: {
      en: "You are the internal auditor reviewing sales returns and credit note controls at Al Rawda Trading Co. One customer account has received an unusually high volume of credit notes for 'damaged/returned' goods, but the warehouse has no matching receiving records. Review the evidence, interview sales and credit control staff, and build a finding.",
      ar: "أنت المدقق الداخلي المكلف بمراجعة ضوابط مرتجعات المبيعات وإشعارات الدائن في شركة الروضة التجارية. تلقى حساب أحد العملاء عدداً كبيراً بشكل غير معتاد من إشعارات الدائن مقابل بضاعة 'تالفة/مرتجعة'، إلا أن المستودع لا يملك أي سجلات استلام مطابقة لذلك. راجع الأدلة، قابل موظفي المبيعات وضبط الائتمان، وابنِ ملاحظتك الرقابية.",
    },
    documents: [
      { id: 'credit-note', icon: 'doc',
        en: { tag: 'Credit Note', title: 'Credit Note CN-2207', rows: [['Customer', 'Al-Manar Retail Stores'], ['Issued by', 'Bader Al-Mutairi, Sales Representative'], ['Amount', 'KD 640.000'], ['Reason given', 'Damaged goods - return accepted'], ['Approved by', 'Sarah Al-Rashidi, Credit Control Officer'], ['Date', '21 Jul 2026']] },
        ar: { tag: 'إشعار دائن', title: 'إشعار دائن رقم CN-2207', rows: [['العميل', 'متاجر المنار للتجزئة'], ['أصدره', 'بدر المطيري، مندوب مبيعات'], ['المبلغ', '640.000 د.ك'], ['السبب المذكور', 'بضاعة تالفة - تم قبول الإرجاع'], ['اعتمدته', 'سارة الراشدي، مسؤولة ضبط الائتمان'], ['التاريخ', '21 يوليو 2026']] } },
      { id: 'credit-note-log', icon: 'doc',
        en: { tag: 'Credit Note Log', title: 'Credit Note Summary - Last 6 Months', rows: [["Al-Manar Retail Stores (Bader's account)", '6 credit notes, total KD 3,420'], ["Bader's other customer accounts (avg.)", '1 credit note, total KD 180'], ['Other sales reps (avg. per customer)', '1 credit note, total KD 150'], ['Pattern', 'All six credit notes cite the same reason: "damaged goods - return accepted"']] },
        ar: { tag: 'سجل إشعارات الدائن', title: 'ملخص إشعارات الدائن - آخر 6 أشهر', rows: [['متاجر المنار للتجزئة (حساب بدر)', '6 إشعارات دائن، بإجمالي 3,420 د.ك'], ['حسابات بدر الأخرى (بالمتوسط)', 'إشعار دائن واحد، بإجمالي 180 د.ك'], ['بقية مندوبي المبيعات (متوسط لكل عميل)', 'إشعار دائن واحد، بإجمالي 150 د.ك'], ['النمط الملاحظ', 'جميع الإشعارات الستة تذكر نفس السبب: "بضاعة تالفة - تم قبول الإرجاع"']] } },
      { id: 'returns-policy', icon: 'scale',
        en: { tag: 'Policy Excerpt', title: 'Sales Returns Policy Section 6.4', rows: [['Step 1', 'Sales representative logs a return request with reason and quantity'], ['Step 2', 'Warehouse issues a Goods Return Note (GRN) once the physical stock is received'], ['Step 3', 'Credit Control posts the credit note only after a GRN is linked'], ['Note', 'In practice, Credit Control may post a credit note marked "urgent" before a GRN is received, to be reconciled later.']] },
        ar: { tag: 'مقتطف من السياسة', title: 'سياسة مرتجعات المبيعات، البند 6.4', rows: [['الخطوة 1', 'يسجل مندوب المبيعات طلب إرجاع مع ذكر السبب والكمية'], ['الخطوة 2', 'يصدر المستودع إشعار استلام مرتجع (GRN) بعد استلام البضاعة فعلياً'], ['الخطوة 3', 'تقوم إدارة ضبط الائتمان بترحيل إشعار الدائن فقط بعد ربطه بإشعار الاستلام'], ['ملاحظة', 'عملياً، يمكن لإدارة ضبط الائتمان ترحيل إشعار دائن مؤشَّر بـ"عاجل" قبل استلام إشعار الاستلام، على أن تتم التسوية لاحقاً.']] } },
      { id: 'receiving-log', icon: 'building',
        en: { tag: 'Warehouse Receiving Log', title: 'Goods Return Note Register - Jul 2026', rows: [['GRNs linked to Al-Manar Retail Stores', '0'], ["GRNs linked to Bader's other accounts", '3, all matching credit notes issued'], ['Note', 'No physical stock from Al-Manar has been received at the warehouse in the last 6 months.']] },
        ar: { tag: 'سجل استلام المستودع', title: 'سجل إشعارات استلام المرتجعات - يوليو 2026', rows: [['إشعارات الاستلام المرتبطة بمتاجر المنار', '0'], ['إشعارات الاستلام المرتبطة بحسابات بدر الأخرى', '3، جميعها مطابقة لإشعارات الدائن الصادرة'], ['ملاحظة', 'لم تُستلم أي بضاعة فعلية من متاجر المنار في المستودع خلال آخر 6 أشهر.']] } },
      { id: 'kickback-messages', icon: 'mail', locked: true,
        en: { tag: 'Correspondence', title: 'Message Thread - Bader & Al-Manar Owner', rows: [['From', 'Bader Al-Mutairi'], ['To', 'Contact saved as "Abu Fahad - Al Manar"'], ['Content', '"Send the usual to my account after the credit note goes through, same as before."'], ['Date', '20 Jul 2026, the day before CN-2207 was issued']] },
        ar: { tag: 'مراسلات', title: 'سلسلة رسائل - بدر ومالك متاجر المنار', rows: [['من', 'بدر المطيري'], ['إلى', 'جهة اتصال محفوظة باسم "أبو فهد - المنار"'], ['المحتوى', '"حوّل المعتاد على حسابي بعد ما يمر إشعار الدائن، زي العادة."'], ['التاريخ', '20 يوليو 2026، اليوم السابق لإصدار الإشعار CN-2207']] } },
    ],
    personas: {
      bader: { en: { name: 'Bader Al-Mutairi', role: 'Sales Representative' }, ar: { name: 'بدر المطيري', role: 'مندوب مبيعات' } },
      sarah: { en: { name: 'Sarah Al-Rashidi', role: 'Credit Control Officer' }, ar: { name: 'سارة الراشدي', role: 'مسؤولة ضبط الائتمان' } },
    },
  },
};

window.CASE_LIST = Object.keys(window.CASES).map((id) => {
  const c = window.CASES[id];
  return { id: id, caseNumber: c.caseNumber, title: c.title, department: c.department, listBlurb: c.listBlurb };
});
